const TermsOfService = () => {
  return (
    <><div className="fixed inset-0 -z-1 pointer-events-none">
     <div className="absolute left-1/2 top-20 -translate-x-1/2 w-245 h-115 bg-linear-to-tr from-pink-800/35 to-transparent rounded-full blur-3xl"></div>
     <div className="absolute right-12 bottom-10 w-105 h-55 bg-linear-to-bl from-red-700/35 to-transparent rounded-full blur-2xl">
     </div>
   </div>
  <div className="min-h-screen pt-32 max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8 pb-28 lg:pb-8">
    <div className="bg-white/6 backdrop-blur-md rounded-2xl p-8 md:p-12 border border-white/10 text-gray-300">
      <div className="text-center mb-16">
        <h1 className="text-4xl md:text-5xl font-bold bg-linear-to-r from-pink-400 to-pink-600 bg-clip-text text-transparent mb-6">
          Terms of Service
        </h1>
        <p className="text-gray-400 text-lg max-w-2xl mx-auto">
          Please read these terms carefully before using Timep.
        </p>
      </div>

      <div className="space-y-8">
        <section>
          <h2 className="text-xl font-medium text-white mb-4">1. Acceptance of Terms</h2>
          <div className="text-gray-300 text-sm leading-relaxed">
            <p>
              By accessing or using <strong>Timep</strong> ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must not use the Platform.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-medium text-white mb-4">2. Description of Service</h2>
          <div className="text-gray-300 text-sm leading-relaxed">
            <p className="mb-4">
              Timep is an AI-powered medical learning platform that generates personalized study tips for medical topics. The Platform includes, but is not limited to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>AI-generated learning tips in various formats (mnemonics, mindmaps, tables, timelines, etc.).</li>
              <li>Personal tip library and history.</li>
              <li>User account management and preferences.</li>
            </ul>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-medium text-white mb-4">3. Eligibility</h2>
          <div className="text-gray-300 text-sm leading-relaxed">
            <p>
              You must be at least 16 years old to use Timep. By creating an account, you confirm that you meet this age requirement and that all information you provide is accurate and up to date.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-medium text-white mb-4">4. User Accounts</h2>
          <div className="text-gray-300 text-sm leading-relaxed">
            <p className="mb-4">When you create an account, you agree to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Provide accurate and complete registration information.</li>
              <li>Maintain the security and confidentiality of your account credentials.</li>
              <li>Notify us immediately of any unauthorized access or use of your account.</li>
              <li>Accept responsibility for all activity that occurs under your account.</li>
            </ul>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-medium text-white mb-4">5. Acceptable Use</h2>
          <div className="text-gray-300 text-sm leading-relaxed">
            <p className="mb-4">You agree not to use the Platform to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Violate any applicable law or regulation.</li>
              <li>Attempt to reverse-engineer, scrape, or copy the Platform's AI systems.</li>
              <li>Submit false, misleading, or harmful content.</li>
              <li>Interfere with or disrupt the integrity or performance of the Platform.</li>
              <li>Access the Platform through automated means without our prior written consent.</li>
            </ul>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-medium text-white mb-4">6. AI-Generated Content Disclaimer</h2>
          <div className="text-gray-300 text-sm leading-relaxed">
            <p className="mb-4">
              The learning tips and content generated by Timep are produced by AI and are intended solely for <strong>educational and study purposes</strong>. They do not constitute medical advice, diagnosis, or treatment.
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Always verify AI-generated content against authoritative medical sources.</li>
              <li>Timep is not a substitute for professional medical judgment or clinical training.</li>
              <li>We do not guarantee the accuracy, completeness, or currentness of any generated content.</li>
            </ul>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-medium text-white mb-4">7. Intellectual Property</h2>
          <div className="text-gray-300 text-sm leading-relaxed">
            <p>
              All intellectual property rights in the Platform, including its design, branding, and underlying AI systems, are owned by Timep or its licensors. You may not reproduce, distribute, or create derivative works from any part of the Platform without our express written permission.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-medium text-white mb-4">8. Termination</h2>
          <div className="text-gray-300 text-sm leading-relaxed">
            <p>
              We reserve the right to suspend or terminate your access to the Platform at any time, without notice, if we believe you have violated these Terms of Service or are using the Platform in a way that could harm others or the integrity of the service.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-medium text-white mb-4">9. Limitation of Liability</h2>
          <div className="text-gray-300 text-sm leading-relaxed">
            <p>
              To the fullest extent permitted by law, Timep shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of or inability to use the Platform, including reliance on AI-generated content for clinical or medical decisions.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-medium text-white mb-4">10. Changes to These Terms</h2>
          <div className="text-gray-300 text-sm leading-relaxed">
            <p>
              We may update these Terms of Service from time to time. When we do, we will revise the "Last updated" date at the bottom of this page. Continued use of the Platform after any changes constitutes your acceptance of the new terms.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-medium text-white mb-4">11. Contact</h2>
          <div className="text-gray-300 text-sm leading-relaxed">
            <p>
              For any questions regarding these Terms of Service, please contact us at{" "}
              <a href="mailto:timepsupport@gmail.com" className="text-pink-400 hover:text-pink-300 transition-colors">
                timepsupport@gmail.com
              </a>.
            </p>
          </div>
        </section>

        <div className="pt-8 border-t border-white/10 text-sm text-gray-500">
          Last updated: 06-01-2026
        </div>
      </div>
    </div>
  </div>  
  </>
  );
};

export default TermsOfService;